[package]
name = "jsona-util"
version = "0.1.0"
edition = "2021"
description = "Shared code for jsona utilities."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
futures = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
time = { version = "0.3", features = ["serde"] }
url = { version = "2.2", features = ["serde"] }
anyhow = "1.0"
atty = "0.2"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
jsona = { path = "../jsona" }
jsona-schema-validator = { path = "../jsona-schema-validator" }
globset = "0.4"
arc-swap = "1.5"
parking_lot = "0.12"
sha1 = "0.10"
ahash = { version = "0.7", features = ["serde"] }
lru = "0.7"
hex = "0.4"
indexmap = { version = "1.9", features = ["serde", "rayon"] }
regex = "1.6"
tap = "1.0"
jsonschema = { version = "0.16", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = [
    "rt",
    "sync",
    "fs",
    "time",
    "io-std",
    "parking_lot",
] }
glob = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", features = ["sync", "parking_lot", "io-util"] }
