name: VSCode Nightly release

on:
  push:
    branches:
    - vscode-nightly

jobs:
  nightly-release:
    name: Nightly publish to Github Releases And Marketplace

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'
        cache-dependency-path: editors/vscode/yarn.lock

    - run: yarn install --frozen-lockfile
      working-directory: editors/vscode

    - name: Set nightly version
      run: |
        version=$(npm version minor --no-git-tag-version | tr -d 'v')
        patch=${{ github.run_number }}
        version_new=${version%.*}.$((patch * 2))
        sed -i 's/^  "version": "'$version'",/  "version": "'$version_new'",/' package.json
      working-directory: editors/vscode

    - run: yarn package -o jsona.vsix --pre-release
      working-directory: editors/vscode
    
    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 'VSCODE Nightly Release $$'
        tag_name: nightly
        draft: false
        prerelease: true
        body: 'This is a nightly release of the vscode-jsona extension.'
        files: editors/vscode/jsona.vsix

    - name: Publish Extension
      run: npx vsce publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --packagePath jsona.vsix --pre-release
      working-directory: editors/vscode