name: Release

on:
  push:
    tags:
    - vscode-v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: Publish to Github Releases And Marketplace

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'

    - run: yarn install --frozen-lockfile
      working-directory: editors/vscode     
    - run: yarn package -o jsona.vsix
      working-directory: editors/vscode     

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.5
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: editors/vscode/jsona.vsix
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Extension
      run: npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --packagePath jsona.vsix
      working-directory: editors/vscode     