name: VSCode Nightly release

on:
  push:
    branches:
    - vscode-nightly

jobs:
  nightly-release:
    name: Nightly publish to Github Releases And Marketplace

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust Toolchain Components
      uses: actions-rs/toolchain@v1
      with:
        components: clippy, rustfmt
        override: true
        toolchain: stable
        target: wasm32-unknown-unknown

    - uses: Swatinem/rust-cache@v1

    - uses: extractions/setup-crate@v1
      with:
        owner: sigoden
        name: argc

    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - run: corepack enable

    - run: argc prepare
    - run: argc wasmjs

    - name: Set nightly version
      run: |
        version=$(npm version minor --no-git-tag-version | tr -d 'v')
        patch=${{ github.run_number }}
        version_new=${version%.*}.$((patch * 2))
        sed -i 's/^  "version": "'$version'",/  "version": "'$version_new'",/' package.json
      working-directory: editors/vscode

    - run: yarn package -o jsona.vsix --pre-release
      working-directory: editors/vscode
    
    - name: Update Nightly Release
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 'VSCODE Nightly Release $$'
        tag_name: nightly
        draft: false
        prerelease: true
        body: 'This is a nightly release of the vscode-jsona extension.'
        files: editors/vscode/jsona.vsix

    - name: Publish Extension
      run: npx vsce publish --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --packagePath jsona.vsix --pre-release
      working-directory: editors/vscode