[package]
name = "jsona-schema"
version = "0.1.0"
edition = "2021"
description = "A jsonschema dsl in jsona format"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = { version = "1.7", features = ["serde"] }
indexmap = { version = "1.9", features = ["serde-1"] }
jsona = { path = "../jsona" }
regex = "1.6"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
