[package]
name = "jsona-schema"
version = "0.1.0"
edition = "2021"
description = "A jsona dsl for jsonschema"

[dependencies]
either = { version = "1.7", features = ["serde"] }
indexmap = { version = "~1.6.2", features = ["serde"] }
jsona = { path = "../jsona", version = "0.4"}
regex = "1.6"
fancy-regex = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
